### ISSUE TITLE
DLR listed twice on consortium page

### ISSUE THREAD

**Issue by sdruskat** [eu-ssi/eussi.org#10]
DLR is listed twice on https://eu-ssi.github.io/eussi.org/consortium/, the only differences being

- different logos used
- duplicate `DLR` string in the right-hand side version (ione included in link, one non-linked right after that).

@caha42 Which one should we use/delete?

**Comment by caha42** [comment]
For the logo the one without the text shall be used. 

For the DLR string - there should be no duplication.

In total: The left version should be kept.
